"""
export.py - 설계 결과 내보내기 라우트
======================================
POST /api/design/export/{candidate_id}   LightTools 매크로 파일 생성
"""

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from backend.api.routes.design import _jobs

router = APIRouter()


class ExportResponse(BaseModel):
    candidate_id: str
    format: str
    content: str


@router.post("/export/{candidate_id}", response_model=ExportResponse)
def export_candidate(candidate_id: str):
    """
    설계 후보를 LightTools 매크로 형식으로 내보내기.
    엔지니어가 LightTools에서 직접 검증할 수 있도록 .lts 매크로 생성.
    """
    # 후보 찾기
    candidate = None
    for job in _jobs.values():
        for c in job.get("candidates", []):
            cid = c.get("id") if isinstance(c, dict) else getattr(c, "id", None)
            if cid == candidate_id:
                candidate = c if isinstance(c, dict) else c.model_dump()
                break
        if candidate:
            break

    if not candidate:
        raise HTTPException(status_code=404, detail=f"Candidate {candidate_id} not found")

    # LightTools 매크로 생성
    p = candidate["params"]
    macro = _generate_lt_macro(p, candidate_id)

    return ExportResponse(
        candidate_id=candidate_id,
        format="lighttools_macro",
        content=macro,
    )


def _generate_lt_macro(params: dict, cid: str) -> str:
    """LightTools Python 매크로 텍스트 생성."""
    return f"""# LightTools Verification Macro
# Candidate: {cid}
# Generated by UDFPS BM Design Studio
# -----------------------------------------

# Design Parameters (um)
delta_bm1 = {params['delta_bm1']:.4f}
delta_bm2 = {params['delta_bm2']:.4f}
w1 = {params['w1']:.4f}
w2 = {params['w2']:.4f}
d = {params['d']:.4f}

# COE Stack (fixed)
cg_thick = {params['cg_thick']:.1f}
encap = {params['z_encap']:.1f}
opd_pitch = {params['opd_pitch']:.1f}
opd_width = {params['opd_width']:.1f}

# --- Setup BM1 apertures (7 pitches) ---
for i in range(7):
    x_center = (i - 3) * opd_pitch + delta_bm1
    # lt.SetAperturePosition(bm1_layer, i, x_center, w1)

# --- Setup BM2 apertures (7 pitches) ---
for i in range(7):
    x_center = (i - 3) * opd_pitch + delta_bm2
    # lt.SetAperturePosition(bm2_layer, i, x_center, w2)

# --- Run simulation ---
# lt.RunRayTrace(n_rays=1000000)
# psf7 = lt.GetOPDIntensity(n_pixels=7)
"""
